In [223]:
import pandas as pd

In [224]:
df1 = pd.read_csv(r"C:\Users\Riri\Downloads\#Opportunity Data - Sheet1.csv")

In [225]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 33)

In [226]:
df1

,pk,opportunity_id,Badge,CareerAddOn,category,code,Cohort,created_at,currency_type,current_editor,DropoutTransaction,duration,duration_type,Eligibility,fee,image_link,is_archived,is_auto_approve,last_date_to_apply,location,long_description,microscholarship,modified_at,name,NotStartedTransaction,Panellist,Reward,role,role_responsibility,short_description,summary,Testimonial,tracking_questions
0,Opportunity#,Opportunity#000000000GBD0AX3Z6VYRG7R75,"{""sk"":""Badge#000000000G87VEXNYKKKTJTKE9"",""ref_...",NaN,Competition,M636023,"{""sk"":""Cohort#000000000GWJV80KJCAEP0JMCF"",""ref...",1.66E+12,USD,amrit@vempower.org,NaN,300,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0,https://www.clipartkey.com/mpngs/m/56-563364_b...,TRUE,TRUE,1.69E+12,NaN,"Your future is in your hands, truly. Ideate an...",500,1.69E+12,Mini Saga 3.0,NaN,NaN,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",NaN,NaN,Express yourself in 50-words!,cc,"{""sk"":""Testimonial#0000000010RY2C6SEZQ3HGA9CM""...",NaN
1,Opportunity#,Opportunity#000000000GFKZ4N696ZF8V2WM8,"{""sk"":""Badge#000000000GAR6YSZ2B71HZJPM3"",""ref_...","{""sk"":""CareerAddOn#000000000G8FT85VQ6BFCT0M0K""...",Career,A463411,"{""sk"":""Cohort#000000000GMAPG3GQV19H288WA"",""ref...",1.66E+12,USD,NaN,NaN,1,years,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0,https://encrypted-tbn0.gstatic.com/images?q=tb...,TRUE,TRUE,1.69E+12,NaN,At GlobalShala we believe that experiential le...,100,1.69E+12,Virtual Internship Facilitator,NaN,NaN,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Facilitator,<html><body><ul><li>Leading and mentoring a gr...,In this role you be impacting young lives whil...,NaN,"{""sk"":""Testimonial#0000000010D46TNR53M1VB684P""...",NaN
2,Opportunity#,Opportunity#0000000010ZFE0ZS22FA3Q62R4,NaN,NaN,Career,A8848RT,"{""sk"":""Cohort#0000000010NSPP283G9WKVMTF1"",""cre...",1.71E+12,NaN,NaN,NaN,30,weeks,NaN,0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,FALSE,1.56E+12,WFM,NaN,0,1.71E+12,Careerwishlist Automation 1710333189352,NaN,NaN,NaN,NaN,Testing and debugging,"Short Description, Explore hands-on defensive ...",NaN,NaN,NaN
3,Opportunity#,Opportunity#000000000GG34EPWZAJ6BDPQKP,"{""sk"":""Badge#000000000GGQG1DZ2TSSHR55G9"",""ref_...",NaN,Internship,I882052,"{""sk"":""Cohort#000000000G5NWDEFZY8WZMG5TM"",""ref...",1.67E+12,USD,NaN,NaN,20,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0,https://excelerateuserprofile.s3.ap-south-1.am...,TRUE,TRUE,1.70E+12,NaN,"In this internship, you will help your sponsor...",1000,1.69E+12,Digital Marketing - Demo,NaN,NaN,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Social Media Analyst,NaN,Explore the best practices and proven strategi...,NaN,"{""sk"":""Testimonial#00000000103FKJAPTGDJ3E9MBV""...",NaN
4,Opportunity#,Opportunity#000000000GQHDFWJ9R1HQJ4WTE,NaN,NaN,Event,E307640,"{""sk"":""Cohort#000000000GG395GEZJKV7T5ZSG"",""ref...",1.66E+12,USD,{},NaN,3,years,"{""sk"":""Eligibility#000000000GF6KQ9RF2HK4CE5K9""...",0,https://excelerateuserprofile.s3.ap-south-1.am...,FALSE,TRUE,1.78E+12,NaN,As technologies such as social media apps and ...,500,1.78E+12,Humanizing Technology: An Introduction to User...,NaN,"{""sk"":""Panellist#000000000GJZDTG56N34DZP205"",""...","{""sk"":""Reward#000000000GPWPT65H92PVBCQ43"",""ref...",NaN,NaN,Students will learn the fundamentals of user e...,NaN,"{""sk"":""Testimonial#0000000010HB3W8EZW550FT6M1""...","{""code"":""Team"",""is_required_for_badge_award"":""..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5728,Opportunity#,Opportunity#0000000010ZWDN5F2Z2G6CH9VN,"{""sk"":""Badge#0000000010GEGWPQKPR8XATV6Y"",""crea...","{""sk"":""CareerAddOn#00000000105CS8N3K8QJ21SR8W""...",Career,AX9ARWF,"{""sk"":""Cohort#0000000010JMNRZYS4P47499ZP"",""cre...",1.70E+12,USD,NaN,NaN,2,months,"{""sk"":""Eligibility#0000000010P10BMC4DRPNHX4JP""...",0,ssdcd,NaN,TRUE,1.70E+12,virtual,sdfvrgfv,1111,1.70E+12,career test opportunity,NaN,NaN,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""cre...",NaN,cdc,sdvfrgfv,NaN,NaN,"{""code"":""Q7AEXTQ"",""question"":""jgfu"",""is_frozen..."
5729,Opportunity#,Opportunity#0000000010VRW600T7H5AXZJ10,"{""sk"":""Badge#000000001041SHEMC0AWG3Q2WS"",""crea...",NaN,Internship,IJ0J8MZ,"{""sk"":""Cohort#00000000109WSKE0F8T7Y02QBT"",""cre...",1.76E+12,INR,NaN,NaN,1,month,"{""sk"":""Eligibility#0000000010A8H1M0ZPMJEQ4SY9""...",0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,FALSE,1.76E+12,Virtual,Long,0,1.76E+12,Rej,NaN,NaN,"{""sk"":""Reward#00000000105JP4MF3PBSMR68EE"",""cre...",R,NaN,Short,NaN,NaN,"{""serial_number"":""1"",""is_required_for_badge_aw..."
5730,Opportunity#,Opportunity#0000000010VS9RA65P8D1FA5ZE,"{""sk"":""Badge#00000000106FDJFC70CATRV9ZH"",""crea...","{""sk"":""CareerAddOn#00000000100JWZQ2J10YF9PYH7""...",Career,A3URJDB,"{""sk"":""Cohort#0000000010JC79F41G4TNK182N"",""cre...",1.71E+12,USD,NaN,NaN,30,weeks,"{""sk"":""Eligibility#0000000010TCM7ZPD02VZ97EMB""...",1,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,FALSE,1.72E+12,virtual,"Long Description, In this internship you will ...",120,1.71E+12,Career Automation 1713529462526,NaN,NaN,"{""sk"":""Reward#0000000010PJY2EEFVNV2FSFKM"",""cre...",NaN,Testing and debugging,"Short Description, Explore hands-on defensive ...",NaN,NaN,"{""is_required_for_badge_award"":""false"",""code"":..."
5731,Opportunity#,Opportunity#0000000010ZZ02VAKM6D63J357,"{""sk"":""Badge#0000000010YZ9F5AMHC3M5B9RV"",""crea...",NaN,Competition,MBBBCXF,"{""sk"":""Cohort#0000000010P5Q2GTA26WBP347Q"",""cre...",1.70E+12,USD,NaN,NaN,30,weeks,"{""sk"":""Eligibility#0000000010MHEF9B2VE0VCGY6Z""...",0,https://excelerateuserprofile.s3.ap-south-1.am...,NaN,FALSE,1.71E+12,virtual,"Long Description, In this internship you will ...",120,1.70E+12,Single Competition Automation 1699002657300,NaN,NaN,"{""sk"":""Reward#000000000GK743JP3HH0P9SRB0"",""cre...",NaN,NaN,"Short Description, Explore hands-on defensive ...",NaN,NaN,"{""is_required_for_badge_award"":""false"",""code"":..."
5732,Opportunity#,Opportunity#0000000010XFNENX1PXV57SW74,"{""sk"":""Badge#0000000010267T036230A6RZB4"",""crea...",NaN,Internship,I1DUNTK,"{""sk"":""Cohort#00000000102F8NMKM9SXFZ7Q7M"",""cre...",1.76E+12,INR,NaN,NaN,1,month,"{""sk"":""Eligibility#0000000010QREC42H8JVNSP4X9""...",0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,FALSE,1.76E+12,Location,Long DescriptionLong DescriptionLong Descripti...,0,1.76E+12,Email one day,NaN,NaN,"{""sk"":""Reward#0000000010FSSXMD4ZP0SVKX5D"",""cre...",Role,NaN,Short DescriptionShort DescriptionShort Descri...,NaN,NaN,"{""serial_number"":""1"",""is_required_for_badge_aw..."

In [227]:
#To view all the columns(It will take time to load)
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)

In [228]:
# First we view the data types and overall info
print("--- DATA TYPES & INFO ---")
print(df1.info())

--- DATA TYPES & INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5733 entries, 0 to 5732
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   pk                     5733 non-null   object
 1   opportunity_id         5733 non-null   object
 2   Badge                  5366 non-null   object
 3   CareerAddOn            908 non-null    object
 4   category               5731 non-null   object
 5   code                   5730 non-null   object
 6   Cohort                 5712 non-null   object
 7   created_at             5730 non-null   object
 8   currency_type          5391 non-null   object
 9   current_editor         217 non-null    object
 10  DropoutTransaction     13 non-null     object
 11  duration               5731 non-null   object
 12  duration_type          5729 non-null   object
 13  Eligibility            5382 non-null   object
 14  fee                    5731 non-null   object
 15  image_link             5725 non-null   object
 16  is_archived            528 non-null    object
 17  is_auto_approve        5731 non-null   object
 18  last_date_to_apply     5730 non-null   object
 19  location               4757 non-null   object
 20  long_description       5387 non-null   object
 21  microscholarship       5730 non-null   object
 22  modified_at            5731 non-null   object
 23  name                   5730 non-null   object
 24  NotStartedTransaction  14 non-null     object
 25  Panellist              1173 non-null   object
 26  Reward                 5366 non-null   object
 27  role                   1893 non-null   object
 28  role_responsibility    1079 non-null   object
 29  short_description      5730 non-null   object
 30  summary                201 non-null    object
 31  Testimonial            851 non-null    object
 32  tracking_questions     4625 non-null   object
dtypes: object(33)
memory usage: 1.4+ MB
None

In [229]:
#the data types are all object form and not defined as either number(int), text(string) or float
#Now we view the missing values per column so we know if we drop them or clean
print("\n--- MISSING VALUES COUNT ---")
print(df1.isnull().sum().sort_values(ascending=False))

--- MISSING VALUES COUNT ---
DropoutTransaction       5720
NotStartedTransaction    5719
summary                  5532
current_editor           5516
is_archived              5205
Testimonial              4882
CareerAddOn              4825
role_responsibility      4654
Panellist                4560
role                     3840
tracking_questions       1108
location                  976
Badge                     367
Reward                    367
Eligibility               351
long_description          346
currency_type             342
Cohort                     21
image_link                  8
duration_type               4
last_date_to_apply          3
code                        3
short_description           3
microscholarship            3
name                        3
created_at                  3
category                    2
duration                    2
modified_at                 2
is_auto_approve             2
fee                         2
opportunity_id              0
pk                          0
dtype: int64

In [230]:
#As you can see the DropoutTransaction, NotStartedTransaction columns have the highest missing values count
missing_percentages = (df1.isnull().sum() / len(df1)) * 100
print("\n--- MISSING VALUES PERCENTAGE ---")
print(missing_percentages.sort_values(ascending=False).head(10))

--- MISSING VALUES PERCENTAGE ---
DropoutTransaction       99.773243
NotStartedTransaction    99.755800
summary                  96.493982
current_editor           96.214896
is_archived              90.790162
Testimonial              85.156114
CareerAddOn              84.161870
role_responsibility      81.179138
Panellist                79.539508
role                     66.980638
dtype: float64

In [231]:
#DropoutTransaction, NotStartedTransaction have 99% missing value while role has 66% hence lesser than the two
#the pk colum contains JSON and HTML codes and not defined data types for data analysis
#the columns with more than 90% missing values are useless for general analysis
#some columns don't have the right data type like the date column (created_at) is not in date format
#Badge, Cohort, and Eligibility column contain JSON strings rather than clean text

In [232]:
#We need to keep only the valid rows before working on columns
#the most corrupted rows are on the pk column so we will filter the dataset to only include rows where the pk column correctly starts with Opportunity#
df1_clean = df1[df1['pk'] == 'Opportunity#'].copy()

In [233]:
df1_clean

,pk,opportunity_id,Badge,CareerAddOn,category,code,Cohort,created_at,currency_type,current_editor,DropoutTransaction,duration,duration_type,Eligibility,fee,image_link,is_archived,is_auto_approve,last_date_to_apply,location,long_description,microscholarship,modified_at,name,NotStartedTransaction,Panellist,Reward,role,role_responsibility,short_description,summary,Testimonial,tracking_questions
0,Opportunity#,Opportunity#000000000GBD0AX3Z6VYRG7R75,"{""sk"":""Badge#000000000G87VEXNYKKKTJTKE9"",""ref_...",NaN,Competition,M636023,"{""sk"":""Cohort#000000000GWJV80KJCAEP0JMCF"",""ref...",1.66E+12,USD,amrit@vempower.org,NaN,300,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0,https://www.clipartkey.com/mpngs/m/56-563364_b...,TRUE,TRUE,1.69E+12,NaN,"Your future is in your hands, truly. Ideate an...",500,1.69E+12,Mini Saga 3.0,NaN,NaN,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",NaN,NaN,Express yourself in 50-words!,cc,"{""sk"":""Testimonial#0000000010RY2C6SEZQ3HGA9CM""...",NaN
1,Opportunity#,Opportunity#000000000GFKZ4N696ZF8V2WM8,"{""sk"":""Badge#000000000GAR6YSZ2B71HZJPM3"",""ref_...","{""sk"":""CareerAddOn#000000000G8FT85VQ6BFCT0M0K""...",Career,A463411,"{""sk"":""Cohort#000000000GMAPG3GQV19H288WA"",""ref...",1.66E+12,USD,NaN,NaN,1,years,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0,https://encrypted-tbn0.gstatic.com/images?q=tb...,TRUE,TRUE,1.69E+12,NaN,At GlobalShala we believe that experiential le...,100,1.69E+12,Virtual Internship Facilitator,NaN,NaN,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Facilitator,<html><body><ul><li>Leading and mentoring a gr...,In this role you be impacting young lives whil...,NaN,"{""sk"":""Testimonial#0000000010D46TNR53M1VB684P""...",NaN
2,Opportunity#,Opportunity#0000000010ZFE0ZS22FA3Q62R4,NaN,NaN,Career,A8848RT,"{""sk"":""Cohort#0000000010NSPP283G9WKVMTF1"",""cre...",1.71E+12,NaN,NaN,NaN,30,weeks,NaN,0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,FALSE,1.56E+12,WFM,NaN,0,1.71E+12,Careerwishlist Automation 1710333189352,NaN,NaN,NaN,NaN,Testing and debugging,"Short Description, Explore hands-on defensive ...",NaN,NaN,NaN
3,Opportunity#,Opportunity#000000000GG34EPWZAJ6BDPQKP,"{""sk"":""Badge#000000000GGQG1DZ2TSSHR55G9"",""ref_...",NaN,Internship,I882052,"{""sk"":""Cohort#000000000G5NWDEFZY8WZMG5TM"",""ref...",1.67E+12,USD,NaN,NaN,20,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0,https://excelerateuserprofile.s3.ap-south-1.am...,TRUE,TRUE,1.70E+12,NaN,"In this internship, you will help your sponsor...",1000,1.69E+12,Digital Marketing - Demo,NaN,NaN,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Social Media Analyst,NaN,Explore the best practices and proven strategi...,NaN,"{""sk"":""Testimonial#00000000103FKJAPTGDJ3E9MBV""...",NaN
4,Opportunity#,Opportunity#000000000GQHDFWJ9R1HQJ4WTE,NaN,NaN,Event,E307640,"{""sk"":""Cohort#000000000GG395GEZJKV7T5ZSG"",""ref...",1.66E+12,USD,{},NaN,3,years,"{""sk"":""Eligibility#000000000GF6KQ9RF2HK4CE5K9""...",0,https://excelerateuserprofile.s3.ap-south-1.am...,FALSE,TRUE,1.78E+12,NaN,As technologies such as social media apps and ...,500,1.78E+12,Humanizing Technology: An Introduction to User...,NaN,"{""sk"":""Panellist#000000000GJZDTG56N34DZP205"",""...","{""sk"":""Reward#000000000GPWPT65H92PVBCQ43"",""ref...",NaN,NaN,Students will learn the fundamentals of user e...,NaN,"{""sk"":""Testimonial#0000000010HB3W8EZW550FT6M1""...","{""code"":""Team"",""is_required_for_badge_award"":""..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5728,Opportunity#,Opportunity#0000000010ZWDN5F2Z2G6CH9VN,"{""sk"":""Badge#0000000010GEGWPQKPR8XATV6Y"",""crea...","{""sk"":""CareerAddOn#00000000105CS8N3K8QJ21SR8W""...",Career,AX9ARWF,"{""sk"":""Cohort#0000000010JMNRZYS4P47499ZP"",""cre...",1.70E+12,USD,NaN,NaN,2,months,"{""sk"":""Eligibility#0000000010P10BMC4DRPNHX4JP""...",0,ssdcd,NaN,TRUE,1.70E+12,virtual,sdfvrgfv,1111,1.70E+12,career test opportunity,NaN,NaN,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""cre...",NaN,cdc,sdvfrgfv,NaN,NaN,"{""code"":""Q7AEXTQ"",""question"":""jgfu"",""is_frozen..."
5729,Opportunity#,Opportunity#0000000010VRW600T7H5AXZJ10,"{""sk"":""Badge#000000001041SHEMC0AWG3Q2WS"",""crea...",NaN,Internship,IJ0J8MZ,"{""sk"":""Cohort#00000000109WSKE0F8T7Y02QBT"",""cre...",1.76E+12,INR,NaN,NaN,1,month,"{""sk"":""Eligibility#0000000010A8H1M0ZPMJEQ4SY9""...",0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,FALSE,1.76E+12,Virtual,Long,0,1.76E+12,Rej,NaN,NaN,"{""sk"":""Reward#00000000105JP4MF3PBSMR68EE"",""cre...",R,NaN,Short,NaN,NaN,"{""serial_number"":""1"",""is_required_for_badge_aw..."
5730,Opportunity#,Opportunity#0000000010VS9RA65P8D1FA5ZE,"{""sk"":""Badge#00000000106FDJFC70CATRV9ZH"",""crea...","{""sk"":""CareerAddOn#00000000100JWZQ2J10YF9PYH7""...",Career,A3URJDB,"{""sk"":""Cohort#0000000010JC79F41G4TNK182N"",""cre...",1.71E+12,USD,NaN,NaN,30,weeks,"{""sk"":""Eligibility#0000000010TCM7ZPD02VZ97EMB""...",1,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,FALSE,1.72E+12,virtual,"Long Description, In this internship you will ...",120,1.71E+12,Career Automation 1713529462526,NaN,NaN,"{""sk"":""Reward#0000000010PJY2EEFVNV2FSFKM"",""cre...",NaN,Testing and debugging,"Short Description, Explore hands-on defensive ...",NaN,NaN,"{""is_required_for_badge_award"":""false"",""code"":..."
5731,Opportunity#,Opportunity#0000000010ZZ02VAKM6D63J357,"{""sk"":""Badge#0000000010YZ9F5AMHC3M5B9RV"",""crea...",NaN,Competition,MBBBCXF,"{""sk"":""Cohort#0000000010P5Q2GTA26WBP347Q"",""cre...",1.70E+12,USD,NaN,NaN,30,weeks,"{""sk"":""Eligibility#0000000010MHEF9B2VE0VCGY6Z""...",0,https://excelerateuserprofile.s3.ap-south-1.am...,NaN,FALSE,1.71E+12,virtual,"Long Description, In this internship you will ...",120,1.70E+12,Single Competition Automation 1699002657300,NaN,NaN,"{""sk"":""Reward#000000000GK743JP3HH0P9SRB0"",""cre...",NaN,NaN,"Short Description, Explore hands-on defensive ...",NaN,NaN,"{""is_required_for_badge_award"":""false"",""code"":..."
5732,Opportunity#,Opportunity#0000000010XFNENX1PXV57SW74,"{""sk"":""Badge#0000000010267T036230A6RZB4"",""crea...",NaN,Internship,I1DUNTK,"{""sk"":""Cohort#00000000102F8NMKM9SXFZ7Q7M"",""cre...",1.76E+12,INR,NaN,NaN,1,month,"{""sk"":""Eligibility#0000000010QREC42H8JVNSP4X9""...",0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,FALSE,1.76E+12,Location,Long DescriptionLong DescriptionLong Descripti...,0,1.76E+12,Email one day,NaN,NaN,"{""sk"":""Reward#0000000010FSSXMD4ZP0SVKX5D"",""cre...",Role,NaN,Short DescriptionShort DescriptionShort Descri...,NaN,NaN,"{""serial_number"":""1"",""is_required_for_badge_aw..."

In [234]:
#We have to drop the columns that are not essential with more than 90% missing values
columns_to_drop = [
    'current_editor', 'DropoutTransaction', 'NotStartedTransaction', 
    'summary', 'is_archived'
]
df1_clean = df1_clean.drop(columns=[col for col in columns_to_drop if col in df1_clean.columns])

In [235]:
#the columns have reduced from 33 to 25
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 33)#the columns have reduced from 33 to 25

In [236]:
#Now we have need to fill the cells with missing data with a placeholder such as 'None' or 'Null' to retain the rows with missing values
#Remember we now have columns with valid values more than 30%
#The cells that we can fill are the ones that we really don't know examples someone's location and their category we don't know if itts carrer or competition etc 
df1_clean['location'] = df1_clean['location'].fillna('Unknown')
df1_clean['category'] = df1_clean['category'].fillna('Unknown')

In [237]:
#The warning is normal we need to let Pandas where to look since the df1_clean is already a data frame and we are trying to edit that same df 
#Pandas recommends using .loc
df1_clean.loc[df1_clean['location'].isna(), 'location'] = 'Unknown'
df1_clean.loc[df1_clean['category'].isna(), 'category'] = 'Unknown'
df1_clean.loc[df1_clean['currency_type'].isna(), 'currency_type'] = 'Unknown'
df1_clean.loc[df1_clean['duration_type'].isna(), 'duration_type'] = 'Unknown'
df1_clean.loc[df1_clean['role'].isna(), 'role'] = 'Unknown'
df1_clean.loc[df1_clean['name'].isna(), 'name'] = 'Not Provided' 
df1_clean.loc[df1_clean['short_description'].isna(), 'short_description'] = 'Not Provided'
df1_clean.loc[df1_clean['long_description'].isna(), 'long_description'] = 'Not Provided'
df1_clean.loc[df1_clean['role_responsibility'].isna(), 'role_responsibility'] = 'Not Provided'

# 1. Fill missing ID-based columns with 'None'
json_cols = ['Badge', 'CareerAddOn', 'Cohort', 'Eligibility', 'Reward', 'Testimonial', 'Panellist', 'tracking_questions']
for col in json_cols:
    if col in df1_clean.columns:
        df1_clean[col] = df1_clean[col].fillna('None')

# 2. Fill numerical columns with 0
df1_clean['fee'] = pd.to_numeric(df1_clean['fee'], errors='coerce').fillna(0)
df1_clean['microscholarship'] = df1_clean['microscholarship'].fillna(0)
df1_clean['duration'] = df1_clean['duration'].fillna(0)

# 3. Fill missing categorical/link columns
df1_clean['code'] = df1_clean['code'].fillna('Unknown')
df1_clean['image_link'] = df1_clean['image_link'].fillna('No Image Provided')
df1_clean['is_auto_approve'] = df1_clean['is_auto_approve'].replace({'NAN': False, 'None': False})
df1_clean['is_auto_approve'] = df1_clean['is_auto_approve'].fillna(False).astype(bool)
date_cols = ['created_at', 'modified_at', 'last_date_to_apply']
df1_clean[date_cols] = df1_clean[date_cols].ffill()
print("Missing values after full cleanup:")
print(df1_clean.isnull().sum())

Missing values after full cleanup:
pk                     0
opportunity_id         0
Badge                  0
CareerAddOn            0
category               0
code                   0
Cohort                 0
created_at             0
currency_type          0
duration               0
duration_type          0
Eligibility            0
fee                    0
image_link             0
is_auto_approve        0
last_date_to_apply     0
location               0
long_description       0
microscholarship       0
modified_at            0
name                   0
Panellist              0
Reward                 0
role                   0
role_responsibility    0
short_description      0
Testimonial            0
tracking_questions     0
dtype: int64

In [238]:
df1_clean

,pk,opportunity_id,Badge,CareerAddOn,category,code,Cohort,created_at,currency_type,duration,duration_type,Eligibility,fee,image_link,is_auto_approve,last_date_to_apply,location,long_description,microscholarship,modified_at,name,Panellist,Reward,role,role_responsibility,short_description,Testimonial,tracking_questions
0,Opportunity#,Opportunity#000000000GBD0AX3Z6VYRG7R75,"{""sk"":""Badge#000000000G87VEXNYKKKTJTKE9"",""ref_...",None,Competition,M636023,"{""sk"":""Cohort#000000000GWJV80KJCAEP0JMCF"",""ref...",1.66E+12,USD,300,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0.0,https://www.clipartkey.com/mpngs/m/56-563364_b...,True,1.69E+12,Unknown,"Your future is in your hands, truly. Ideate an...",500,1.69E+12,Mini Saga 3.0,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Unknown,Not Provided,Express yourself in 50-words!,"{""sk"":""Testimonial#0000000010RY2C6SEZQ3HGA9CM""...",None
1,Opportunity#,Opportunity#000000000GFKZ4N696ZF8V2WM8,"{""sk"":""Badge#000000000GAR6YSZ2B71HZJPM3"",""ref_...","{""sk"":""CareerAddOn#000000000G8FT85VQ6BFCT0M0K""...",Career,A463411,"{""sk"":""Cohort#000000000GMAPG3GQV19H288WA"",""ref...",1.66E+12,USD,1,years,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0.0,https://encrypted-tbn0.gstatic.com/images?q=tb...,True,1.69E+12,Unknown,At GlobalShala we believe that experiential le...,100,1.69E+12,Virtual Internship Facilitator,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Facilitator,<html><body><ul><li>Leading and mentoring a gr...,In this role you be impacting young lives whil...,"{""sk"":""Testimonial#0000000010D46TNR53M1VB684P""...",None
2,Opportunity#,Opportunity#0000000010ZFE0ZS22FA3Q62R4,None,None,Career,A8848RT,"{""sk"":""Cohort#0000000010NSPP283G9WKVMTF1"",""cre...",1.71E+12,Unknown,30,weeks,None,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,1.56E+12,WFM,Not Provided,0,1.71E+12,Careerwishlist Automation 1710333189352,None,None,Unknown,Testing and debugging,"Short Description, Explore hands-on defensive ...",None,None
3,Opportunity#,Opportunity#000000000GG34EPWZAJ6BDPQKP,"{""sk"":""Badge#000000000GGQG1DZ2TSSHR55G9"",""ref_...",None,Internship,I882052,"{""sk"":""Cohort#000000000G5NWDEFZY8WZMG5TM"",""ref...",1.67E+12,USD,20,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,1.70E+12,Unknown,"In this internship, you will help your sponsor...",1000,1.69E+12,Digital Marketing - Demo,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Social Media Analyst,Not Provided,Explore the best practices and proven strategi...,"{""sk"":""Testimonial#00000000103FKJAPTGDJ3E9MBV""...",None
4,Opportunity#,Opportunity#000000000GQHDFWJ9R1HQJ4WTE,None,None,Event,E307640,"{""sk"":""Cohort#000000000GG395GEZJKV7T5ZSG"",""ref...",1.66E+12,USD,3,years,"{""sk"":""Eligibility#000000000GF6KQ9RF2HK4CE5K9""...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,1.78E+12,Unknown,As technologies such as social media apps and ...,500,1.78E+12,Humanizing Technology: An Introduction to User...,"{""sk"":""Panellist#000000000GJZDTG56N34DZP205"",""...","{""sk"":""Reward#000000000GPWPT65H92PVBCQ43"",""ref...",Unknown,Not Provided,Students will learn the fundamentals of user e...,"{""sk"":""Testimonial#0000000010HB3W8EZW550FT6M1""...","{""code"":""Team"",""is_required_for_badge_award"":""..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5728,Opportunity#,Opportunity#0000000010ZWDN5F2Z2G6CH9VN,"{""sk"":""Badge#0000000010GEGWPQKPR8XATV6Y"",""crea...","{""sk"":""CareerAddOn#00000000105CS8N3K8QJ21SR8W""...",Career,AX9ARWF,"{""sk"":""Cohort#0000000010JMNRZYS4P47499ZP"",""cre...",1.70E+12,USD,2,months,"{""sk"":""Eligibility#0000000010P10BMC4DRPNHX4JP""...",0.0,ssdcd,True,1.70E+12,virtual,sdfvrgfv,1111,1.70E+12,career test opportunity,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""cre...",Unknown,cdc,sdvfrgfv,None,"{""code"":""Q7AEXTQ"",""question"":""jgfu"",""is_frozen..."
5729,Opportunity#,Opportunity#0000000010VRW600T7H5AXZJ10,"{""sk"":""Badge#000000001041SHEMC0AWG3Q2WS"",""crea...",None,Internship,IJ0J8MZ,"{""sk"":""Cohort#00000000109WSKE0F8T7Y02QBT"",""cre...",1.76E+12,INR,1,month,"{""sk"":""Eligibility#0000000010A8H1M0ZPMJEQ4SY9""...",0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,1.76E+12,Virtual,Long,0,1.76E+12,Rej,None,"{""sk"":""Reward#00000000105JP4MF3PBSMR68EE"",""cre...",R,Not Provided,Short,None,"{""serial_number"":""1"",""is_required_for_badge_aw..."
5730,Opportunity#,Opportunity#0000000010VS9RA65P8D1FA5ZE,"{""sk"":""Badge#00000000106FDJFC70CATRV9ZH"",""crea...","{""sk"":""CareerAddOn#00000000100JWZQ2J10YF9PYH7""...",Career,A3URJDB,"{""sk"":""Cohort#0000000010JC79F41G4TNK182N"",""cre...",1.71E+12,USD,30,weeks,"{""sk"":""Eligibility#0000000010TCM7ZPD02VZ97EMB""...",1.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,1.72E+12,virtual,"Long Description, In this internship you will ...",120,1.71E+12,Career Automation 1713529462526,None,"{""sk"":""Reward#0000000010PJY2EEFVNV2FSFKM"",""cre...",Unknown,Testing and debugging,"Short Description, Explore hands-on defensive ...",None,"{""is_required_for_badge_award"":""false"",""code"":..."
5731,Opportunity#,Opportunity#0000000010ZZ02VAKM6D63J357,"{""sk"":""Badge#0000000010YZ9F5AMHC3M5B9RV"",""crea...",None,Competition,MBBBCXF,"{""sk"":""Cohort#0000000010P5Q2GTA26WBP347Q"",""cre...",1.70E+12,USD,30,weeks,"{""sk"":""Eligibility#0000000010MHEF9B2VE0VCGY6Z""...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,1.71E+12,virtual,"Long Description, In this internship you will ...",120,1.70E+12,Single Competition Automation 1699002657300,None,"{""sk"":""Reward#000000000GK743JP3HH0P9SRB0"",""cre...",Unknown,Not Provided,"Short Description, Explore hands-on defensive ...",None,"{""is_required_for_badge_award"":""false"",""code"":..."
5732,Opportunity#,Opportunity#0000000010XFNENX1PXV57SW74,"{""sk"":""Badge#0000000010267T036230A6RZB4"",""crea...",None,Internship,I1DUNTK,"{""sk"":""Cohort#00000000102F8NMKM9SXFZ7Q7M"",""cre...",1.76E+12,INR,1,month,"{""sk"":""Eligibility#0000000010QREC42H8JVNSP4X9""...",0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,1.76E+12,Location,Long DescriptionLong DescriptionLong Descripti...,0,1.76E+12,Email one day,None,"{""sk"":""Reward#0000000010FSSXMD4ZP0SVKX5D"",""cre...",Role,Not Provided,Short DescriptionShort DescriptionShort Descri...,None,"{""serial_number"":""1"",""is_required_for_badge_aw..."

In [239]:
#We also need to change the date string which are scientific notations that represent milliseconds (1.66E+12) to date format
def parse_timestamp(val):
    try:
        return pd.to_datetime(float(val), unit='ms', errors='coerce')
    except:
        return pd.NaT

In [240]:
#Now we need to apply these function to our date columns ie created_at, modified_at
df1_clean = df1_clean.copy()
#This is to ensure the .loc warning doestn't appear
def parse_timestamp(val):
    try:
        # Convert the string '1.66E+12' into a number
        num = float(val)
        # Convert the number into a datetime object
        return pd.to_datetime(num, unit='ms')
    except (ValueError, TypeError):
        # If the cell is completely empty or corrupted, return NaT safely
        return pd.NaT

# Now your original code will work perfectly
df1_clean['created_at'] = df1_clean['created_at'].apply(parse_timestamp)
df1_clean['modified_at'] = df1_clean['modified_at'].apply(parse_timestamp)
df1_clean['last_date_to_apply'] = df1_clean['last_date_to_apply'].apply(parse_timestamp)

In [241]:
df1_clean

,pk,opportunity_id,Badge,CareerAddOn,category,code,Cohort,created_at,currency_type,duration,duration_type,Eligibility,fee,image_link,is_auto_approve,last_date_to_apply,location,long_description,microscholarship,modified_at,name,Panellist,Reward,role,role_responsibility,short_description,Testimonial,tracking_questions
0,Opportunity#,Opportunity#000000000GBD0AX3Z6VYRG7R75,"{""sk"":""Badge#000000000G87VEXNYKKKTJTKE9"",""ref_...",None,Competition,M636023,"{""sk"":""Cohort#000000000GWJV80KJCAEP0JMCF"",""ref...",2022-08-08 23:06:40,USD,300,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0.0,https://www.clipartkey.com/mpngs/m/56-563364_b...,True,2023-07-22 04:26:40,Unknown,"Your future is in your hands, truly. Ideate an...",500,2023-07-22 04:26:40,Mini Saga 3.0,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Unknown,Not Provided,Express yourself in 50-words!,"{""sk"":""Testimonial#0000000010RY2C6SEZQ3HGA9CM""...",None
1,Opportunity#,Opportunity#000000000GFKZ4N696ZF8V2WM8,"{""sk"":""Badge#000000000GAR6YSZ2B71HZJPM3"",""ref_...","{""sk"":""CareerAddOn#000000000G8FT85VQ6BFCT0M0K""...",Career,A463411,"{""sk"":""Cohort#000000000GMAPG3GQV19H288WA"",""ref...",2022-08-08 23:06:40,USD,1,years,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0.0,https://encrypted-tbn0.gstatic.com/images?q=tb...,True,2023-07-22 04:26:40,Unknown,At GlobalShala we believe that experiential le...,100,2023-07-22 04:26:40,Virtual Internship Facilitator,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Facilitator,<html><body><ul><li>Leading and mentoring a gr...,In this role you be impacting young lives whil...,"{""sk"":""Testimonial#0000000010D46TNR53M1VB684P""...",None
2,Opportunity#,Opportunity#0000000010ZFE0ZS22FA3Q62R4,None,None,Career,A8848RT,"{""sk"":""Cohort#0000000010NSPP283G9WKVMTF1"",""cre...",2024-03-09 16:00:00,Unknown,30,weeks,None,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2019-06-08 13:20:00,WFM,Not Provided,0,2024-03-09 16:00:00,Careerwishlist Automation 1710333189352,None,None,Unknown,Testing and debugging,"Short Description, Explore hands-on defensive ...",None,None
3,Opportunity#,Opportunity#000000000GG34EPWZAJ6BDPQKP,"{""sk"":""Badge#000000000GGQG1DZ2TSSHR55G9"",""ref_...",None,Internship,I882052,"{""sk"":""Cohort#000000000G5NWDEFZY8WZMG5TM"",""ref...",2022-12-02 16:53:20,USD,20,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,2023-11-14 22:13:20,Unknown,"In this internship, you will help your sponsor...",1000,2023-07-22 04:26:40,Digital Marketing - Demo,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Social Media Analyst,Not Provided,Explore the best practices and proven strategi...,"{""sk"":""Testimonial#00000000103FKJAPTGDJ3E9MBV""...",None
4,Opportunity#,Opportunity#000000000GQHDFWJ9R1HQJ4WTE,None,None,Event,E307640,"{""sk"":""Cohort#000000000GG395GEZJKV7T5ZSG"",""ref...",2022-08-08 23:06:40,USD,3,years,"{""sk"":""Eligibility#000000000GF6KQ9RF2HK4CE5K9""...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,2026-05-28 20:26:40,Unknown,As technologies such as social media apps and ...,500,2026-05-28 20:26:40,Humanizing Technology: An Introduction to User...,"{""sk"":""Panellist#000000000GJZDTG56N34DZP205"",""...","{""sk"":""Reward#000000000GPWPT65H92PVBCQ43"",""ref...",Unknown,Not Provided,Students will learn the fundamentals of user e...,"{""sk"":""Testimonial#0000000010HB3W8EZW550FT6M1""...","{""code"":""Team"",""is_required_for_badge_award"":""..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5728,Opportunity#,Opportunity#0000000010ZWDN5F2Z2G6CH9VN,"{""sk"":""Badge#0000000010GEGWPQKPR8XATV6Y"",""crea...","{""sk"":""CareerAddOn#00000000105CS8N3K8QJ21SR8W""...",Career,AX9ARWF,"{""sk"":""Cohort#0000000010JMNRZYS4P47499ZP"",""cre...",2023-11-14 22:13:20,USD,2,months,"{""sk"":""Eligibility#0000000010P10BMC4DRPNHX4JP""...",0.0,ssdcd,True,2023-11-14 22:13:20,virtual,sdfvrgfv,1111,2023-11-14 22:13:20,career test opportunity,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""cre...",Unknown,cdc,sdvfrgfv,None,"{""code"":""Q7AEXTQ"",""question"":""jgfu"",""is_frozen..."
5729,Opportunity#,Opportunity#0000000010VRW600T7H5AXZJ10,"{""sk"":""Badge#000000001041SHEMC0AWG3Q2WS"",""crea...",None,Internship,IJ0J8MZ,"{""sk"":""Cohort#00000000109WSKE0F8T7Y02QBT"",""cre...",2025-10-09 08:53:20,INR,1,month,"{""sk"":""Eligibility#0000000010A8H1M0ZPMJEQ4SY9""...",0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2025-10-09 08:53:20,Virtual,Long,0,2025-10-09 08:53:20,Rej,None,"{""sk"":""Reward#00000000105JP4MF3PBSMR68EE"",""cre...",R,Not Provided,Short,None,"{""serial_number"":""1"",""is_required_for_badge_aw..."
5730,Opportunity#,Opportunity#0000000010VS9RA65P8D1FA5ZE,"{""sk"":""Badge#00000000106FDJFC70CATRV9ZH"",""crea...","{""sk"":""CareerAddOn#00000000100JWZQ2J10YF9PYH7""...",Career,A3URJDB,"{""sk"":""Cohort#0000000010JC79F41G4TNK182N"",""cre...",2024-03-09 16:00:00,USD,30,weeks,"{""sk"":""Eligibility#0000000010TCM7ZPD02VZ97EMB""...",1.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2024-07-03 09:46:40,virtual,"Long Description, In this internship you will ...",120,2024-03-09 16:00:00,Career Automation 1713529462526,None,"{""sk"":""Reward#0000000010PJY2EEFVNV2FSFKM"",""cre...",Unknown,Testing and debugging,"Short Description, Explore hands-on defensive ...",None,"{""is_required_for_badge_award"":""false"",""code"":..."
5731,Opportunity#,Opportunity#0000000010ZZ02VAKM6D63J357,"{""sk"":""Badge#0000000010YZ9F5AMHC3M5B9RV"",""crea...",None,Competition,MBBBCXF,"{""sk"":""Cohort#0000000010P5Q2GTA26WBP347Q"",""cre...",2023-11-14 22:13:20,USD,30,weeks,"{""sk"":""Eligibility#0000000010MHEF9B2VE0VCGY6Z""...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,2024-03-09 16:00:00,virtual,"Long Description, In this internship you will ...",120,2023-11-14 22:13:20,Single Competition Automation 1699002657300,None,"{""sk"":""Reward#000000000GK743JP3HH0P9SRB0"",""cre...",Unknown,Not Provided,"Short Description, Explore hands-on defensive ...",None,"{""is_required_for_badge_award"":""false"",""code"":..."
5732,Opportunity#,Opportunity#0000000010XFNENX1PXV57SW74,"{""sk"":""Badge#0000000010267T036230A6RZB4"",""crea...",None,Internship,I1DUNTK,"{""sk"":""Cohort#00000000102F8NMKM9SXFZ7Q7M"",""cre...",2025-10-09 08:53:20,INR,1,month,"{""sk"":""Eligibility#0000000010QREC42H8JVNSP4X9""...",0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2025-10-09 08:53:20,Location,Long DescriptionLong DescriptionLong Descripti...,0,2025-10-09 08:53:20,Email one day,None,"{""sk"":""Reward#0000000010FSSXMD4ZP0SVKX5D"",""cre...",Role,Not Provided,Short DescriptionShort DescriptionShort Descri...,None,"{""serial_number"":""1"",""is_required_for_badge_aw..."

In [242]:
#To address the True andfalse issues, years we need to enforce standard casing and format
df1_clean['category'] = df1_clean['category'].astype(str).str.title()
df1_clean['duration_type'] = df1_clean['duration_type'].astype(str).str.lower()
df1_clean['is_auto_approve'] = df1_clean['is_auto_approve'].astype(str).str.upper()

In [243]:
 #To ensure consistency we need to ensure that the once that have not been changed are changed effectively TRUE will change to True
df1_clean['is_auto_approve'] = df1_clean['is_auto_approve'].replace({'TRUE': True, 'FALSE': False})

C:\Users\Riri\AppData\Local\Temp\ipykernel_16184\1769409062.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1_clean['is_auto_approve'] = df1_clean['is_auto_approve'].replace({'TRUE': True, 'FALSE': False})

In [244]:
df1_clean

,pk,opportunity_id,Badge,CareerAddOn,category,code,Cohort,created_at,currency_type,duration,duration_type,Eligibility,fee,image_link,is_auto_approve,last_date_to_apply,location,long_description,microscholarship,modified_at,name,Panellist,Reward,role,role_responsibility,short_description,Testimonial,tracking_questions
0,Opportunity#,Opportunity#000000000GBD0AX3Z6VYRG7R75,"{""sk"":""Badge#000000000G87VEXNYKKKTJTKE9"",""ref_...",None,Competition,M636023,"{""sk"":""Cohort#000000000GWJV80KJCAEP0JMCF"",""ref...",2022-08-08 23:06:40,USD,300,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0.0,https://www.clipartkey.com/mpngs/m/56-563364_b...,True,2023-07-22 04:26:40,Unknown,"Your future is in your hands, truly. Ideate an...",500,2023-07-22 04:26:40,Mini Saga 3.0,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Unknown,Not Provided,Express yourself in 50-words!,"{""sk"":""Testimonial#0000000010RY2C6SEZQ3HGA9CM""...",None
1,Opportunity#,Opportunity#000000000GFKZ4N696ZF8V2WM8,"{""sk"":""Badge#000000000GAR6YSZ2B71HZJPM3"",""ref_...","{""sk"":""CareerAddOn#000000000G8FT85VQ6BFCT0M0K""...",Career,A463411,"{""sk"":""Cohort#000000000GMAPG3GQV19H288WA"",""ref...",2022-08-08 23:06:40,USD,1,years,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0.0,https://encrypted-tbn0.gstatic.com/images?q=tb...,True,2023-07-22 04:26:40,Unknown,At GlobalShala we believe that experiential le...,100,2023-07-22 04:26:40,Virtual Internship Facilitator,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Facilitator,<html><body><ul><li>Leading and mentoring a gr...,In this role you be impacting young lives whil...,"{""sk"":""Testimonial#0000000010D46TNR53M1VB684P""...",None
2,Opportunity#,Opportunity#0000000010ZFE0ZS22FA3Q62R4,None,None,Career,A8848RT,"{""sk"":""Cohort#0000000010NSPP283G9WKVMTF1"",""cre...",2024-03-09 16:00:00,Unknown,30,weeks,None,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2019-06-08 13:20:00,WFM,Not Provided,0,2024-03-09 16:00:00,Careerwishlist Automation 1710333189352,None,None,Unknown,Testing and debugging,"Short Description, Explore hands-on defensive ...",None,None
3,Opportunity#,Opportunity#000000000GG34EPWZAJ6BDPQKP,"{""sk"":""Badge#000000000GGQG1DZ2TSSHR55G9"",""ref_...",None,Internship,I882052,"{""sk"":""Cohort#000000000G5NWDEFZY8WZMG5TM"",""ref...",2022-12-02 16:53:20,USD,20,minutes,"{""sk"":""Eligibility#000000000GNQAM21BYCRBX5Z27""...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,2023-11-14 22:13:20,Unknown,"In this internship, you will help your sponsor...",1000,2023-07-22 04:26:40,Digital Marketing - Demo,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""ref...",Social Media Analyst,Not Provided,Explore the best practices and proven strategi...,"{""sk"":""Testimonial#00000000103FKJAPTGDJ3E9MBV""...",None
4,Opportunity#,Opportunity#000000000GQHDFWJ9R1HQJ4WTE,None,None,Event,E307640,"{""sk"":""Cohort#000000000GG395GEZJKV7T5ZSG"",""ref...",2022-08-08 23:06:40,USD,3,years,"{""sk"":""Eligibility#000000000GF6KQ9RF2HK4CE5K9""...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,2026-05-28 20:26:40,Unknown,As technologies such as social media apps and ...,500,2026-05-28 20:26:40,Humanizing Technology: An Introduction to User...,"{""sk"":""Panellist#000000000GJZDTG56N34DZP205"",""...","{""sk"":""Reward#000000000GPWPT65H92PVBCQ43"",""ref...",Unknown,Not Provided,Students will learn the fundamentals of user e...,"{""sk"":""Testimonial#0000000010HB3W8EZW550FT6M1""...","{""code"":""Team"",""is_required_for_badge_award"":""..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5728,Opportunity#,Opportunity#0000000010ZWDN5F2Z2G6CH9VN,"{""sk"":""Badge#0000000010GEGWPQKPR8XATV6Y"",""crea...","{""sk"":""CareerAddOn#00000000105CS8N3K8QJ21SR8W""...",Career,AX9ARWF,"{""sk"":""Cohort#0000000010JMNRZYS4P47499ZP"",""cre...",2023-11-14 22:13:20,USD,2,months,"{""sk"":""Eligibility#0000000010P10BMC4DRPNHX4JP""...",0.0,ssdcd,True,2023-11-14 22:13:20,virtual,sdfvrgfv,1111,2023-11-14 22:13:20,career test opportunity,None,"{""sk"":""Reward#000000000GP9G70RKA2V5WXN5B"",""cre...",Unknown,cdc,sdvfrgfv,None,"{""code"":""Q7AEXTQ"",""question"":""jgfu"",""is_frozen..."
5729,Opportunity#,Opportunity#0000000010VRW600T7H5AXZJ10,"{""sk"":""Badge#000000001041SHEMC0AWG3Q2WS"",""crea...",None,Internship,IJ0J8MZ,"{""sk"":""Cohort#00000000109WSKE0F8T7Y02QBT"",""cre...",2025-10-09 08:53:20,INR,1,month,"{""sk"":""Eligibility#0000000010A8H1M0ZPMJEQ4SY9""...",0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2025-10-09 08:53:20,Virtual,Long,0,2025-10-09 08:53:20,Rej,None,"{""sk"":""Reward#00000000105JP4MF3PBSMR68EE"",""cre...",R,Not Provided,Short,None,"{""serial_number"":""1"",""is_required_for_badge_aw..."
5730,Opportunity#,Opportunity#0000000010VS9RA65P8D1FA5ZE,"{""sk"":""Badge#00000000106FDJFC70CATRV9ZH"",""crea...","{""sk"":""CareerAddOn#00000000100JWZQ2J10YF9PYH7""...",Career,A3URJDB,"{""sk"":""Cohort#0000000010JC79F41G4TNK182N"",""cre...",2024-03-09 16:00:00,USD,30,weeks,"{""sk"":""Eligibility#0000000010TCM7ZPD02VZ97EMB""...",1.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2024-07-03 09:46:40,virtual,"Long Description, In this internship you will ...",120,2024-03-09 16:00:00,Career Automation 1713529462526,None,"{""sk"":""Reward#0000000010PJY2EEFVNV2FSFKM"",""cre...",Unknown,Testing and debugging,"Short Description, Explore hands-on defensive ...",None,"{""is_required_for_badge_award"":""false"",""code"":..."
5731,Opportunity#,Opportunity#0000000010ZZ02VAKM6D63J357,"{""sk"":""Badge#0000000010YZ9F5AMHC3M5B9RV"",""crea...",None,Competition,MBBBCXF,"{""sk"":""Cohort#0000000010P5Q2GTA26WBP347Q"",""cre...",2023-11-14 22:13:20,USD,30,weeks,"{""sk"":""Eligibility#0000000010MHEF9B2VE0VCGY6Z""...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,2024-03-09 16:00:00,virtual,"Long Description, In this internship you will ...",120,2023-11-14 22:13:20,Single Competition Automation 1699002657300,None,"{""sk"":""Reward#000000000GK743JP3HH0P9SRB0"",""cre...",Unknown,Not Provided,"Short Description, Explore hands-on defensive ...",None,"{""is_required_for_badge_award"":""false"",""code"":..."
5732,Opportunity#,Opportunity#0000000010XFNENX1PXV57SW74,"{""sk"":""Badge#0000000010267T036230A6RZB4"",""crea...",None,Internship,I1DUNTK,"{""sk"":""Cohort#00000000102F8NMKM9SXFZ7Q7M"",""cre...",2025-10-09 08:53:20,INR,1,month,"{""sk"":""Eligibility#0000000010QREC42H8JVNSP4X9""...",0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2025-10-09 08:53:20,Location,Long DescriptionLong DescriptionLong Descripti...,0,2025-10-09 08:53:20,Email one day,None,"{""sk"":""Reward#0000000010FSSXMD4ZP0SVKX5D"",""cre...",Role,Not Provided,Short DescriptionShort DescriptionShort Descri...,None,"{""serial_number"":""1"",""is_required_for_badge_aw..."

In [245]:
#the columns have reduced from 33 to 25
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 33)

In [246]:
#We need to make these {"sk":"Badge#0000000010267T036230A6RZB4","crea... and <html><body><ul><li>Leadin... readable
#We need to import REGULAR EXPRESSIONS AS RE
# It is a built-in Python library used for searching, matching, and manipulating specific patterns of text.
#We will use it to Stripping HTML tags and Extracting IDs which are in JSON
import re

In [247]:
#Starting with html
def remove_html_tags(text):
    if isinstance(text, str):
        clean = re.compile('<.*?>')
        return re.sub(clean, '', text)
    return text

# Apply the function to relevant columns
df1_clean['role_responsibility'] = df1_clean['role_responsibility'].apply(remove_html_tags)
df1_clean['long_description'] = df1_clean['long_description'].apply(remove_html_tags)

In [248]:
#Next the JSON
def extract_sk_ids(text):
    if pd.isna(text):
        return 'None'
    # This regex finds all text placed immediately after "sk":"
    matches = re.findall(r'"sk":"([^"]+)"', str(text))
    
    if matches:
        return ', '.join(matches) # Joins multiple IDs with a comma if there are more than one
    return 'None'

# 2. We define the columns that have this messy JSON format
json_columns = [
    'Badge', 'Cohort', 'Eligibility', 'Testimonial', 
    'Reward', 'CareerAddOn', 'Panellist', 'tracking_questions'
]

# 3. Apply the function to clean those columns in your dataframe
for col in json_columns:
    if col in df1_clean.columns:
        df1_clean[col] = df1_clean[col].apply(extract_sk_ids)

In [249]:
df1_clean

,pk,opportunity_id,Badge,CareerAddOn,category,code,Cohort,created_at,currency_type,duration,duration_type,Eligibility,fee,image_link,is_auto_approve,last_date_to_apply,location,long_description,microscholarship,modified_at,name,Panellist,Reward,role,role_responsibility,short_description,Testimonial,tracking_questions
0,Opportunity#,Opportunity#000000000GBD0AX3Z6VYRG7R75,Badge#000000000G87VEXNYKKKTJTKE9,None,Competition,M636023,Cohort#000000000GWJV80KJCAEP0JMCF,2022-08-08 23:06:40,USD,300,minutes,"Eligibility#000000000GNQAM21BYCRBX5Z27, Eligib...",0.0,https://www.clipartkey.com/mpngs/m/56-563364_b...,True,2023-07-22 04:26:40,Unknown,"Your future is in your hands, truly. Ideate an...",500,2023-07-22 04:26:40,Mini Saga 3.0,None,"Reward#000000000GP9G70RKA2V5WXN5B, Reward#0000...",Unknown,Not Provided,Express yourself in 50-words!,"Testimonial#0000000010RY2C6SEZQ3HGA9CM, Testim...",None
1,Opportunity#,Opportunity#000000000GFKZ4N696ZF8V2WM8,Badge#000000000GAR6YSZ2B71HZJPM3,CareerAddOn#000000000G8FT85VQ6BFCT0M0K,Career,A463411,Cohort#000000000GMAPG3GQV19H288WA,2022-08-08 23:06:40,USD,1,years,"Eligibility#000000000GNQAM21BYCRBX5Z27, Eligib...",0.0,https://encrypted-tbn0.gstatic.com/images?q=tb...,True,2023-07-22 04:26:40,Unknown,At GlobalShala we believe that experiential le...,100,2023-07-22 04:26:40,Virtual Internship Facilitator,None,"Reward#000000000GP9G70RKA2V5WXN5B, Reward#0000...",Facilitator,Leading and mentoring a group of 5-10 students...,In this role you be impacting young lives whil...,Testimonial#0000000010D46TNR53M1VB684P,None
2,Opportunity#,Opportunity#0000000010ZFE0ZS22FA3Q62R4,None,None,Career,A8848RT,Cohort#0000000010NSPP283G9WKVMTF1,2024-03-09 16:00:00,Unknown,30,weeks,None,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2019-06-08 13:20:00,WFM,Not Provided,0,2024-03-09 16:00:00,Careerwishlist Automation 1710333189352,None,None,Unknown,Testing and debugging,"Short Description, Explore hands-on defensive ...",None,None
3,Opportunity#,Opportunity#000000000GG34EPWZAJ6BDPQKP,Badge#000000000GGQG1DZ2TSSHR55G9,None,Internship,I882052,"Cohort#000000000G5NWDEFZY8WZMG5TM, Cohort#0000...",2022-12-02 16:53:20,USD,20,minutes,"Eligibility#000000000GNQAM21BYCRBX5Z27, Eligib...",0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,2023-11-14 22:13:20,Unknown,"In this internship, you will help your sponsor...",1000,2023-07-22 04:26:40,Digital Marketing - Demo,None,"Reward#000000000GP9G70RKA2V5WXN5B, Reward#0000...",Social Media Analyst,Not Provided,Explore the best practices and proven strategi...,"Testimonial#00000000103FKJAPTGDJ3E9MBV, Testim...",None
4,Opportunity#,Opportunity#000000000GQHDFWJ9R1HQJ4WTE,None,None,Event,E307640,"Cohort#000000000GG395GEZJKV7T5ZSG, Cohort#0000...",2022-08-08 23:06:40,USD,3,years,Eligibility#000000000GF6KQ9RF2HK4CE5K9,0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,2026-05-28 20:26:40,Unknown,As technologies such as social media apps and ...,500,2026-05-28 20:26:40,Humanizing Technology: An Introduction to User...,Panellist#000000000GJZDTG56N34DZP205,"Reward#000000000GPWPT65H92PVBCQ43, Reward#0000...",Unknown,Not Provided,Students will learn the fundamentals of user e...,"Testimonial#0000000010HB3W8EZW550FT6M1, Testim...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5728,Opportunity#,Opportunity#0000000010ZWDN5F2Z2G6CH9VN,Badge#0000000010GEGWPQKPR8XATV6Y,CareerAddOn#00000000105CS8N3K8QJ21SR8W,Career,AX9ARWF,Cohort#0000000010JMNRZYS4P47499ZP,2023-11-14 22:13:20,USD,2,months,Eligibility#0000000010P10BMC4DRPNHX4JP,0.0,ssdcd,True,2023-11-14 22:13:20,virtual,sdfvrgfv,1111,2023-11-14 22:13:20,career test opportunity,None,Reward#000000000GP9G70RKA2V5WXN5B,Unknown,cdc,sdvfrgfv,None,None
5729,Opportunity#,Opportunity#0000000010VRW600T7H5AXZJ10,Badge#000000001041SHEMC0AWG3Q2WS,None,Internship,IJ0J8MZ,Cohort#00000000109WSKE0F8T7Y02QBT,2025-10-09 08:53:20,INR,1,month,Eligibility#0000000010A8H1M0ZPMJEQ4SY9,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2025-10-09 08:53:20,Virtual,Long,0,2025-10-09 08:53:20,Rej,None,Reward#00000000105JP4MF3PBSMR68EE,R,Not Provided,Short,None,None
5730,Opportunity#,Opportunity#0000000010VS9RA65P8D1FA5ZE,Badge#00000000106FDJFC70CATRV9ZH,CareerAddOn#00000000100JWZQ2J10YF9PYH7,Career,A3URJDB,Cohort#0000000010JC79F41G4TNK182N,2024-03-09 16:00:00,USD,30,weeks,Eligibility#0000000010TCM7ZPD02VZ97EMB,1.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2024-07-03 09:46:40,virtual,"Long Description, In this internship you will ...",120,2024-03-09 16:00:00,Career Automation 1713529462526,None,"Reward#0000000010PJY2EEFVNV2FSFKM, Reward#0000...",Unknown,Testing and debugging,"Short Description, Explore hands-on defensive ...",None,None
5731,Opportunity#,Opportunity#0000000010ZZ02VAKM6D63J357,Badge#0000000010YZ9F5AMHC3M5B9RV,None,Competition,MBBBCXF,"Cohort#0000000010P5Q2GTA26WBP347Q, Cohort#0000...",2023-11-14 22:13:20,USD,30,weeks,Eligibility#0000000010MHEF9B2VE0VCGY6Z,0.0,https://excelerateuserprofile.s3.ap-south-1.am...,True,2024-03-09 16:00:00,virtual,"Long Description, In this internship you will ...",120,2023-11-14 22:13:20,Single Competition Automation 1699002657300,None,"Reward#000000000GK743JP3HH0P9SRB0, Reward#0000...",Unknown,Not Provided,"Short Description, Explore hands-on defensive ...",None,None
5732,Opportunity#,Opportunity#0000000010XFNENX1PXV57SW74,Badge#0000000010267T036230A6RZB4,None,Internship,I1DUNTK,Cohort#00000000102F8NMKM9SXFZ7Q7M,2025-10-09 08:53:20,INR,1,month,Eligibility#0000000010QREC42H8JVNSP4X9,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,True,2025-10-09 08:53:20,Location,Long DescriptionLong DescriptionLong Descripti...,0,2025-10-09 08:53:20,Email one day,None,Reward#0000000010FSSXMD4ZP0SVKX5D,Role,Not Provided,Short DescriptionShort DescriptionShort Descri...,None,None

In [250]:
#Lastly before we save lets drop duplicate rows and pk column
df1_clean = df1_clean.drop_duplicates()
df1_clean = df1_clean.drop(columns=['pk'])

In [251]:
# Now lets Export the fully cleaned dataset to a new CSV file
df1_clean.to_csv('Cleaned_Opportunity_Data4.csv', index=False)
print("Data cleaning complete. File saved as 'Cleaned_Opportunity_Data.csv'.")

Data cleaning complete. File saved as 'Cleaned_Opportunity_Data.csv'.